export const INITIAL_BATTLE_STATE = 'INITIAL_BATTLE_STATE';
export const UPDATE_BATTLE_STATE = 'UPDATE_BATTLE_STATE';
export const REQUEST_DECISION = 'REQUEST_DECISION';
export const DECISON_ERROR = 'DECISON_ERROR';
